### ISSUE TITLE
Battle Engine

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/hero-quest#1]
Implement the core features of a battle engine, showcasing a complete battle, with a winner on the end.

## Requirements
- Each event of the **Battle** must be visible;
- The **Battle** should have two sides, with one **Combatant** each;
- Each **Combatant** should be capable of using basic attack **Actions**;
- Basic attack Actions are physical attacks that does damage equal to **d6** plus a Hero's **Strength**;
- The battle should be separated in turns, starting with the **Combatant** with superior **Initiative**
- **Initiative** is value generated by a **d20 roll** plus the Hero's **Dexterity** attribute value, done at the start of a **Battle**
- A **Combatant** is a **Hero** on a Battle, with a **Initiative** value associated
- A **Battle** ends when only one of the sides has **Combatants** alive

![hero quest - class](https://user-images.githubusercontent.com/15656072/41825272-e00ad472-77f3-11e8-933b-2f2f051885fc.png)

## Acceptance
- A Battle with two Heroes of equal attributes, should be completed when computed for at maximum 100 turns, showing a clear winner.

## Tasks
- [x] Implement a Walking Skeleton based on the Acceptance Scenario #2 
- [x] Hero Module #4 
- [x] Action Module #5 
- [x] Battle Module #6 
- [x] Command Line Application #8 
- [x] Review and document formulas used to compute battles #3
