### ISSUE TITLE
Quality gate issues

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/hero-quest#12]
After adjusting the code coverage to Jacoco and refactoring some parts of the application, the code coverage dropped below 80% and some other issues were detected by [Sonar](https://sonarcloud.io/project/issues?id=br.com.miguelmf%3Ahero-quest&resolved=false). Those need to be adjusted to keep the code base healthy.

## Tasks

- [x] Implement private default constructor on `Stringfy`
- [x] Remove stacktrace print at `Stringfy.getFieldValue`
- [x] Remove bad assignment at `Hero.getMaxHpIfHpWasNotSet`
- [x] Implement multi-catch at `Stringfy.getFieldValue`
- [x] Improve up constructors and factory methods of  `Hero`, maintaining only 7 arguments at maximum
- [x] Implement tests to achieve code coverage of at least 70%
