### ISSUE TITLE
 Action Module

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/hero-quest#5]
Implement the action module, containing one default action: the basic attack.

- A **BasicAttack** is a simple **Action** that does damage as `damage = d6 + strength`

## Acceptance

- A Hero should be able to attack another Hero with a basic attack, computing damage.

## Tasks

- [x] Implement the `BasicAttack` action
- [x] Implement a basic `NPCActionSelector` that only does basic attacks
- [x] Update the project model as necessary

## Related

- Child of #1

**Comment by Miguel-Fontes** [comment]
## Battle Engine Sequence Diagram

![hero quest - battle sequence 2](https://user-images.githubusercontent.com/15656072/41693565-45f7578a-74dc-11e8-9bf9-7270dd0c95e1.png)
