### ISSUE TITLE
Command Line Application

### ISSUE THREAD

**Issue by Miguel-Fontes** [Miguel-Fontes/hero-quest#8]
Implement a application that integrates the other modules with a CLI that shows the events of a battle, no interaction is needed for the MVP. It is interesting that:

- The names of the combatants change
- The battle is won by different sides each time

So, some randomness is welcome.

## Acceptance

- It should be possible to run the application via command line, with no parameters and watch a battle being evaluated by the battle engine.

## Tasks 

- [x] Implement main module (application shell)
- [x] Implement a reporting feature, showing each step of the Battle (delaying at each step, if adequate)
- [x] Update the model as necessary
- [x] Refactor code

## Related

- Child of #1
